// <auto-generated />
namespace UniversityLMS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class temp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(temp));
        
        string IMigrationMetadata.Id
        {
            get { return "201401191908355_temp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
