// <auto-generated />
namespace UniversityLMS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddedInstructor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedInstructor));
        
        string IMigrationMetadata.Id
        {
            get { return "201401191832045_AddedInstructor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
