// <auto-generated />
namespace UniversityLMS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddedRequiredFieldsInstructorStudent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedRequiredFieldsInstructorStudent));
        
        string IMigrationMetadata.Id
        {
            get { return "201401282111528_AddedRequiredFieldsInstructorStudent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
